docker-master:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_CLI_EXPERIMENTAL: "enabled"
    REGISTRY_IMAGE: "registry.gitlab.com/vondruska/345securitymqtt"
  before_script:
    - docker 
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker run --rm --privileged hypriot/qemu-register
  script:
    - docker build --pull -f Dockerfile.arm -t "$CI_REGISTRY_IMAGE" .
    - docker tag "$REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:arm-$CI_JOB_ID"
  only:
    - master
